name: Push Comple Time Files to New Repo

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Navigate to repo
      run: cd $GITHUB_WORKSPACE
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install deps
      run: yarn
    - name: Clean for Build
      run: yarn clean
    - name: Build docs
      run: yarn build

    - name: Pushes to another repository
      id: push_directory
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
      with:
        source_file: 'public'
        destination_folder: src/this_site_name
        destination_repo: 'adam-at-brown/ws-static-base'
        destination_branch: test-branch-name
        user_name: adam-at-brown
        user_email: adam_holtzman@brown.edu

    - name: Open Module Pull Request
      id: pull-request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.WSS_2 }}
        path: charlie
        commit-message: "Update test passer stuff with compiled code"
        branch: feature/ws-passer2
        title: "Make site go now better"
        body: "Changes from ${{ github.event.pull_request.html_url }}"
